import 'package:flutter/material.dart';

/// Centralized category/wallet icon registry (§7-9).
/// SQLite stores only the stable string [key]; widgets resolve via [iconFor].
/// Never store IconData in the database.
abstract final class CategoryIcons {
  /// All selectable keys (used by the custom-category icon picker).
  static const List<String> all = [
    'cash',
    'bank',
    'card',
    'savings',
    'salary',
    'freelance',
    'allowance',
    'investment',
    'refund',
    'other_income',
    'shopping_cart',
    'groceries',
    'restaurant',
    'coffee',
    'fastfood',
    'taxi',
    'louage',
    'bus',
    'metro',
    'tram',
    'fuel',
    'car',
    'travel',
    'bolt',
    'electricity',
    'water',
    'sonede',
    'steg',
    'wifi',
    'internet',
    'phone',
    'mobile',
    'shirt',
    'clothing',
    'devices',
    'electronics',
    'home',
    'rent',
    'health',
    'entertainment',
    'gym',
    'book',
    'gift',
    'subscription',
    'other',
  ];

  static bool isKnown(String key) => _map.containsKey(key);

  /// Unknown keys fall back to [other] so old/new data never breaks UI.
  static IconData iconFor(String? key) => _map[key] ?? _map['other']!;

  static const Map<String, IconData> _map = {
    'cash': Icons.payments,
    'bank': Icons.account_balance,
    'card': Icons.credit_card,
    'savings': Icons.savings,
    'salary': Icons.work,
    'freelance': Icons.laptop_mac,
    'allowance': Icons.account_balance_wallet,
    'investment': Icons.trending_up,
    // Refund uses a direction-neutral coin glyph: the undo arrow would
    // need per-locale mirroring at every render site.
    'refund': Icons.monetization_on,
    'other_income': Icons.attach_money,
    'shopping_cart': Icons.shopping_cart,
    'restaurant': Icons.restaurant,
    'coffee': Icons.coffee,
    'fastfood': Icons.fastfood,
    'taxi': Icons.local_taxi,
    'louage': Icons.airport_shuttle,
    'bus': Icons.directions_bus,
    'directions_bus': Icons.directions_bus,
    'metro': Icons.subway,
    'tram': Icons.tram,
    'fuel': Icons.local_gas_station,
    'car': Icons.directions_car,
    'travel': Icons.flight,
    'bolt': Icons.bolt,
    'electricity': Icons.bolt,
    'steg': Icons.bolt,
    'water': Icons.water_drop,
    'sonede': Icons.water_drop,
    'wifi': Icons.wifi,
    'internet': Icons.wifi,
    'phone': Icons.smartphone,
    'mobile': Icons.smartphone,
    'shirt': Icons.checkroom,
    'clothing': Icons.checkroom,
    'devices': Icons.devices,
    'electronics': Icons.devices,
    'groceries': Icons.shopping_cart,
    'home': Icons.home,
    'rent': Icons.key,
    'health': Icons.health_and_safety,
    'entertainment': Icons.movie,
    'gym': Icons.fitness_center,
    'book': Icons.book,
    'gift': Icons.card_giftcard,
    'subscription': Icons.autorenew,
    'transfer': Icons.swap_horiz,
    'other': Icons.category,
  };
}
